// <auto-generated />
using System;
using BancoCajero.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BancoCajero.Infrastructure.Migrations
{
    [DbContext(typeof(CajeroDbContext))]
    [Migration("20251114154410_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BancoCajero.Domain.Entidades.CuentaBancaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("BancoCajero.Domain.Entidades.CuentaBancaria", b =>
                {
                    b.OwnsOne("BancoCajero.Domain.Entidades.Persona", "Titular", b1 =>
                        {
                            b1.Property<Guid>("CuentaBancariaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Apellidos")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Dni")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CuentaBancariaId");

                            b1.ToTable("Cuentas");

                            b1.WithOwner()
                                .HasForeignKey("CuentaBancariaId");
                        });

                    b.Navigation("Titular")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
